---
title: "About"
---

Hello! I'm Jillian Allison. I graduated from the University of California, Santa Barbara in 2022 with a degree in Earth Science and an emphasis in Geohydrology. 

As an undergraduate at UCSB, I was a board member and a mentor for the new Earth Science department mentoring program (GEMSS). Here, I organized community events and panels focused on academic and professional development and received the Departmental Leadership Award for my efforts. 

I am currently pursuing a Master\'s degree in Environmental Data Science from the Bren School of Environmental Science and Management at UCSB. I am interested in the confluence of data science and water quality. I have held water quality monitoring roles at the Cheadle Center for Biodiversity and Ecological Restoration, Valley Water, and the Santa Barbara Channelkeeper. In these positions, I developed expertise in field hydrology, specifically surface water quality and its impact on the surrounding environment. Moving forward, I hope to continue collecting and analyzing hydrological data to find solutions to water resources issues.
