---
title: "Water Data Justice" 
description: "Hydrologic Data Gaps, Data Inaccessibility, and Citizen Science" 
author: 
    - name: Jillian Allison
      url: https://jilliannallison.github.io
      affiliation: MEDS
      affiliation-url: https://ucsb-meds.github.io/
date: 2022-11-29
categories: [MEDS, Environmental Data Justice]
citation: 
  url: https://jilliannallison.github.io/posts/2022-11-29-water-data-justice
draft: true
---

#### Introduction

Data has become increasingly important in modern policy decisions, especially those related to  environmental problems.^1^ For this reason, it is crucial to consider several issues surrounding this "datafication":

-   Data Justice: how does our collection and distribution of data impact historically marginalized communities?^2^

-   Data gaps & quality of data: Is our data sufficient to make policy decisions?

-   Accessibility of data: Can key stakeholders access the data we collect and use to make policy decisions? Privacy: What data should be collected and made available, and to who? 

For the most part, people view data as the fundamental truth. I'm sure you've heard the phrase, "numbers don't lie!" In reality, we choose what data to collect, where to collect this data from, and how to process that data, meaning all data is subject to societal values and should be interpreted within the context of our culture. We must also be critical of how the data we do (or do not) collect will influence individuals and the physical environment. 

Hydrologic data is a key tool for managing our most valuable resource (water, not data). Like all data, water data is subject to our societal values. This has impacts on environmental justice, funding, and data accessibility, all of which hinder efforts to maintain healthy watersheds. 

In this post, I will specifically address environmental data gaps and inaccessibility as these issues relate to hydrology. I will then discuss citizen science's role in lessening the impacts of these issues on watershed health.

#### Environmental Data Gaps

Generally, environmental data is temporally and geographically limited, which renders it less effective in informing policy decisions. In Information as Power: Democratizing Environmental Data^3^, Dr. Annie Brett emphasizes the importance of long-term, integrated national environmental data. She writes:

*"Yes, new technologies are generating new data on environmental conditions. But systemic challenges throughout the data lifecycle prevent this data from being used effectively to inform decision-making. Data is often redundant, inaccessible, and unavailable to key stakeholders."*\

Without reliable, long-term environmental data, it is difficult to study long term trends that could inform government climate action. Brett's proposed solution to these environmental data gaps is for federal agencies to maintain long term, accessible environmental data in integrated databases. 

Thanks to the Clean Water Act, water quality data comprises some of the United States' most reliable environmental datasets, but water quality is still impacted by temporal and geographic data gaps. 

#### Case Study: Nitrogen Data

In *Closing the Environmental Data Gap* ^4^, Robin O'Malley et al. provide a case study on nitrogen pollution, demonstrating the impacts of insufficient environmental data. Nitrogen is released into the environment by fossil fuels, fertilizers, and sewage. Nitrogen in runoff leads to well-documented coastal dead zones, and can cause health problems for children if present in drinking water. There are vast geographic gaps in nitrogen pollution data, making it difficult to mitigate the effects of this pollution, and to quantify measures of success in this mitigation. If we are not able to quantify nitrogen pollution and the environmental parameters it affects, how can we craft policy to create positive change in an increasingly data-driven world? How will we know if our policy change has been effective without reliable, widespread environmental data? 

#### Citizen Science

Citizen Science (CS) is becoming an increasingly useful source of environmental data. CS requires relatively little funding while increasing the scale of data collection and involving the community in the first step of modern environmental decision-making. 

CS also requires open data to encourage continued volunteer participation. 83% of citizen science projects studied by Alex de Sherbinin et al. in *The Critical Importance of Citizen Science Data*^5^ shared the data with the volunteers. 

Community members are arguably the most important stakeholders in environmental issues, and by including citizens in data collection and environmental decision-making, we can move towards overcoming environmental justice issues. 

Contrary to popular belief, CS can be a very reliable source of data. The vast majority of projects studied in Sherbinin et al. 2021^5^ had strong methods for ensuring data quality- 94% of projects used one method or more. 

\
That being said, Citizen Science does not solve all of our environmental data issues. Depending on the scale, CS does not always resolve the need for large-scale, cohesive datasets. CS also raises issues of equity; it is a privilege to have free time and resources to volunteer as a citizen scientist. 

#### Case Study: The Santa Barbara Channelkeeper

The Santa Barbara Channelkeeper's (SBCK) Stream Team Program^6^ on California's Central Coast is one successful example of citizen science in water quality data collection. Volunteers, accompanied by trained staff, measure key water quality parameters in dozens of streams in the Santa Barbara area. Local government agencies regularly use this data to inform policy decisions. This data has been used to identify pollution hot spots, which SBCK and local governments collaboratively restored. 

There are several key aspects of this program that contribute to its accuracy and its success in engaging the community in watershed management:

-   SBCK sends a trained staff member with each volunteer group to ensure proper data collection. This is known to improve the accuracy of citizen science data.^5^

-   SBCK provides transportation to measurement sites, which greatly reduces the financial burden on volunteers and expands the potential reach of this volunteer program. 

-   SBCK treats volunteers to a free lunch following the sampling events. This provides some form of compensation to volunteers, which many citizen science volunteer programs do not. 

-   Data collected by SBCK is publicly available for download in .csv format, and data can be explored directly on their website without any programming experience.^7^

#### References

1.  Gitelman, Lisa. *"Raw Data" is an Oxymoron.* Cambridge, MA: MIT Press, 2013. 
2.  "Why Research and Data Justice," Coalition of Communities of Color, accessed November 14, 2022, <https://www.coalitioncommunitiescolor.org/-why-research-data-justice>.
3.  Brett, Annie. "Information as Power: Democratizing Environmental Data." *Utah L. Rev.* 127 (2022). 
4.  Marsh, Anne S., Christine Negra, and Robin O'Malley. "Closing the Environmental Data Gap." *Issues in Science and Technology* 25, no. 3 (Spring 2009).
5.  de Sherbinin, Alex., Anne Bowser, Tyng-Ruey Chuang, Caren Cooper, Finn Danielsen, Rorie Edmunds, Peter Elias, Elaine Faustman, Carolynne Hultquist, Rosy Mondardini, Ioana Popescu, Adenike Shonowo, and Kishore Sivakumar. "The Critical Importance of Citizen Science Data." *Frontiers in Climate* (March, 2021). 3:650760. doi: 10.3389/fclim.2021.650760
6.  "Stream Team." Santa Barbara Channelkeeper. Accessed November 15, 2022. <https://www.sbck.org/our-work/field-work/stream-team/> . 
7.  "Stream Team Data Portal." Santa Barbara Channelkeeper. Accessed November 15, 2022. <https://www.sbck.org/our-work/field-work/stream-team/stream-team-data-portal/> .\
    \
    \
    \

\
\
